### DISCUSSION TITLE
Why does connector need to change the hostname?

### DISCUSSION THREAD

**Discussion by phaseOne** [balena-labs-projects/connector#53] [Q&A]
I see that `entry.sh` changes the device's hostname. Is this necessary for the services to function?

I'd prefer to handle hostname configuration myself with other methods, and `connector`'s default hostname changing behavior is conflicting with that. I'm currently importing the `connector` image in my repo's `docker-compose.yml` like so, but the only way I'd be able to prevent the hostname from changing is to fork the project:

```yaml
  connector:
    image:  balenablocks/connector
    restart: always
    labels:
      io.balena.features.balena-api: '1'
    privileged: true  # necessary to change container hostname
```

If the `connector` project instead adds [balenablocks/hostname](https://github.com/balenablocks/hostname) to its `docker-compose.yml`, it would allow those who import `connector` more flexibility, while retaining the default behavior, and the `connector` service wouldn't need to run in privileged mode. Example:

```yaml
version: '2.1'

services:
  connector:
    image: balenablocks/connector:raspberrypi3
    restart: always
    labels:
      io.balena.features.balena-api: '1' # necessary to discover services
    ports:
      - "8080" # only necessary if using ExternalHttpListener (see below)
  hostname:
    image: bh.cr/g_tomas_migone1/hostname
    restart: no                               # Required to avoid container restarting indefinitely
    labels:
      io.balena.features.supervisor-api: 1    # Required to interact with the supervisor
    environment:
      SET_HOSTNAME: uuid
```
